# Generated by Django 4.0.5 on 2022-08-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('CandidateName', models.CharField(max_length=255)),
                ('CandidateId', models.AutoField(primary_key=True, serialize=False)),
                ('CandidateClass', models.CharField(choices=[('9A', ' 9A'), ('9B', ' 9B'), ('10A', ' 10A'), ('10B', ' 10B'), ('11A', ' 11A'), ('11B', ' 11B'), ('11C', ' 11C'), ('12A', ' 12A'), ('12B', ' 12B')], max_length=3)),
                ('Post', models.TextField(choices=[('head_boy', 'Head Boy'), ('head_girl', 'Head Girl'), ('sports_captain', 'Sports Captain'), ('activity_captain', 'Activity Captain')])),
                ('Votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=255)),
                ('StudentId', models.CharField(max_length=255)),
                ('StudentClass', models.CharField(choices=[('9A', ' 9A'), ('9B', ' 9B'), ('10A', ' 10A'), ('10B', ' 10B'), ('11A', ' 11A'), ('11B', ' 11B'), ('11C', ' 11C'), ('12A', ' 12A'), ('12B', ' 12B')], max_length=3)),
                ('Roll', models.IntegerField()),
                ('Voted', models.BooleanField(default=False)),
            ],
        ),
    ]
