# Generated by Django 4.0.5 on 2022-08-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='CandidateName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='StudentName',
            field=models.CharField(max_length=100),
        ),
    ]
